config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "foods#index"
  resources :users, only: [:edit, :update]
  resources :foods
  resources :managements
end

app/models/activity.rb
class Activity < ActiveHash::Base
  self.data = [
      {id: 1, name: 'Ⅰ=1.50 生活の大部分が座位で、静的な活動が中心の場合'}, {id: 2, name: 'Ⅱ=1.75 座位中心の仕事だが、職場内での移動や立位での作業・接客等、または通勤・家事、軽いスポーツ等を含む場合'}, {id: 3, name: 'Ⅲ=2.00 移動や立位の多い仕事への従事者。あるいは、スポーツなど余暇における活発な運動習慣をもっている場合'}
  ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :managements, through: :management_foods
  has_many :users
  has_many :management_foods
  validates :name, presence: true, uniqueness: true
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
      {id: 1, name: '男性'}, {id: 2, name: '女性'}
  ]
end

app/models/management.rb
class Management < ApplicationRecord
  belongs_to :user
  has_many :management_foods
  has_many :foods, through: :management_foods, dependent: :delete_all
  mount_uploader :image, ImageUploader
end

app/models/management_food.rb
class ManagementFood < ApplicationRecord
  belongs_to :management
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  belongs_to :management, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:name, :calorie, :carbohydrate, :protein, :fat]
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :age, :height, :weight, :activity])
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @foods = Food.all.order('name ASC')
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save
      redirect_to root_path, notice: '登録に成功しました'
    else
      render :new
    end
  end

  def show
    @food = Food.find(params[:id])
  end

  def destroy
    food = Food.find(params[:id])
    food.destroy
    redirect_to root_path
  end

  def edit
    @food = Food.find(params[:id])
  end

  def update
    food = Food.find(params[:id])
    food.update(food_params)
    redirect_to root_path
  end
  
  private
  def food_params
    params.require(:food).permit(:id, :name, :calorie, :carbohydrate, :protein, :fat, :salt_equivalent, :dietary_fiber)#.merge(user_id: current_user.id)
  end
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :set_management, only: [:show, :edit, :update, :destroy]
  # before_action :total, only: [:index]

  require 'date'

  def index
    @managements = Management.where(user_id: current_user.id)
  end

  def show
  end

  def new
    @management = Management.new
    return nil if params[:keyword] == ""
    @foods = Food.where(['name LIKE ?', "%#{params[:keyword]}%"])
    respond_to do |format|
      format.html
      format.json
    end
  end

  def edit
  end

  def create
    @management = Management.new(management_params)
    if @management.save
      redirect_to managements_path, notice: '登録しました'
    else
      render :new
    end
  end

  def update
    if @management.update(management_params)
      redirect_to managements_path, notice: '更新しました'
    else
      render :edit
    end
  end

  def destroy
    @management.destroy
    redirect_to managements_path, notice: '削除しました' 
  end

  private
    def set_management
      @management = Management.find(params[:id])
    end

    # def total
    #   @today_managements = Management.where(day: Date.current).where(user_id: current_user.id).includes(:foods)
    #   @total_calorie = 0
    #   @total_carbohydrate = 0
    #   @total_protein = 0
    #   @total_fat = 0
    #   @total_salt_equivalent = 0
    #   @total_dietary_fiber = 0
    #   @today_managements.each do |today|
    #     today.foods.each do |food|
    #       @total_calorie += food.calorie
    #       @total_carbohydrate += food.carbohydrate
    #       @total_protein += food.protein
    #       @total_fat += food.fat
    #       @total_salt_equivalent += food.salt_equivalent
    #       @total_dietary_fiber += food.dietary_fiber
    #     end
    #   end
    # end

    def management_params
      params.require(:management).permit(:title, :day, food_ids: []).merge(user_id: current_user.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :gender, :age, :height, :weight, :activity)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_header.html.haml
.header.clearfix
  %h2.header__title
    = "食事管理アプリ"
    %h3.header__name
      = current_user.name
    %ul.header__lists
      %li.list
        = link_to "食べ物追加", new_food_path, class: 'btn'
      %li.list
        = link_to "食事管理", managements_path(current_user), class: 'btn'
      %li.list
        = link_to "アカウント編集", edit_user_path(current_user), class: 'btn'

app/views/foods/_main_contents.html.haml
.main_contents
  .writings
    .writing
      .writing__title
        %h3 カロリーとは？
      .writing__content
        %p
          摂取する食物から得られる栄養学的熱量と、運動や基礎代謝によって消費される熱量について適用され、生物が生理的に代謝したエネルギー1カロリーは空気中での酸化反応（燃焼）によって発生した熱量1カロリーと等しいと定義される。
          栄養学ではカロリーを1000倍のキロカロリー kcal（キロカロリー）と表記するのが一般的である。
          カロリーは、生きていくのに必要とするエネルギーのこと。
          %br 
            一日に必要なエネルギー量は、
            %span 「総エネルギー量(kcal)＝ 基礎代謝量（kcal） × 身体活動レベル」
            で求められる。
          *このアプリでは基礎代謝量をハリス-ベネディクトの式の簡易式を用いています。
    .writing
      .writing__title
        %h3 糖質とは？
      .writing__content
        %p
          栄養学上は炭水化物は糖質と食物繊維の総称として扱われており、消化酵素では分解できずエネルギー源にはなりにくい食物繊維を除いたものを糖質と呼んでいる。三大栄養素のひとつとして炭水化物の語を用いるときは、主に糖質を指す
          主な役割として脳、身体を動かすエネルギーとして使われる。
          %br 
            %span 1グラムにつき4キロカロリー
            のエネルギーがある。
    .writing
      .writing__title
        %h3 タンパク質とは？
      .writing__content
        %p
          20種類存在するL-アミノ酸が鎖状に多数連結（重合）してできた高分子化合物であり、生物の重要な構成成分のひとつである。
          タンパク質は身体をつくる役割も果たしている。
          %br 
            %span 1グラムにつき4キロカロリー
            のエネルギーがある。
    .writing
      .writing__title
        %h3 食物繊維とは？
      .writing__content
        %p
          食べ物の中に含まれ、人の消化酵素で消化することのできない物質。
          整腸作用など身体の中で有用な働きをすることが注目され、第6の栄養素といわれることもある。
    .writing
      .writing__title
        %h3 ナトリウムとは？
      .writing__content
        %p
          人体に必要なミネラルの一種で、浸透圧の調整などの働きをする。主に食塩の形で摂取される。
    .writing
      .writing__title
        %h3 BMIとは？
      .writing__content
        %p
          ボディマス指数（ボディマスしすう）とは、体重と身長の関係から算出される、ヒトの肥満度を表す体格指数である。
          一般にBMI (Body Mass Index) と呼ばれ
          %span 「BMI ＝ 体重（kg）/ 身長（m）× 身長（m）」
          で求められる。
    .writing
      .writing__title
        %h3 PFC比とは？
      .writing__content
        %p
        生活習慣病の発症予防とその重症化予防を目的としたエネルギー産生栄養素バランスの目標量の範囲を示したもの。
        %br 
          %span 「たんぱく質（P）：13～20％　脂質（F）：20～30％　炭水化物（C）：50～65％」
          を摂取することがより健康的な食生活とされています。

app/views/foods/_side_bar.html.haml
.side_bar
  .side_bar__title
    %h3 登録一覧
  .side_bar__lists
    - @foods.each do |food|
      %ul.foods-lists
        %li.food-list
          = link_to "#{food.name}", food_path(food.id), class: "food-list__name"

app/views/foods/edit.html.haml
.food-form
  %h1 編集
  = form_for @food do |f|
    -if @food.errors.any?
      .food-foom__errors
        %h2= "#{@food.errors.full_messages.count}件のエラーが発生しました。"
        %ul
          - @food.errors.full_messages.each do |message|
            %li= message
    .food-form__field.clearfix
      .food-form__field--left
        = f.label :name, "食べ物名", class: 'food-form__label'
      .food-form__field--right
        = f.text_field :name, step: "0.1", class: 'food_name food-form__input', placeholder: " 食べ物名 を入力してください", required: ""
      .food-form__field--left
        = f.label :calorie, "カロリー(kcal)", class: 'food-form__label' 
      .food-form__field--right
        = f.number_field :calorie, class: 'food_calorie food-form__input', placeholder: " カロリー (半角数字) を入力してください", required: "", min: "0", max: "10000"
      .food-form__field--left
        = f.label :carbohydrate, "糖質(g)", class: 'food-form__label'
      .food-form__field--right
        = f.number_field :carbohydrate, step: "0.1", class: 'food_carbohydrate food-form__input', placeholder: "  糖  質  (半角数字)) を入力してください", required: "", min: "0", max: "1000"
      .food-form__field--left
        = f.label :protein, "タンパク質(g)", class: 'food-form__label' 
      .food-form__field--right
        = f.number_field :protein, step: "0.1", class: 'food_protein food-form__input', placeholder: "タンパク質 (半角数字) を入力してください", required: "", min: "0", max: "1000"
      .food-form__field--left
        = f.label :fat, "脂質(g)", class: 'food-form__label' 
      .food-form__field--right
        = f.number_field :fat, step: "0.1", class: 'food_fat food-form__input', placeholder: "  脂  質  (半角数字) を入力してください", required: "", min: "0", max: "1000"
      .food-form__field--left
        = f.label :salt_equivalent, "食塩相当量(g)", class: 'food-form__label' 
      .food-form__field--right
        = f.number_field :salt_equivalent, step: "0.1", class: 'food_salt_equivalent food-form__input', placeholder: "食塩相当量 (半角数字) を入力してください", required: "", min: "0", max: "1000"
      .food-form__field--left
        = f.label :dietary_fiber, "食物繊維(g)", class: 'food-form__label' 
      .food-form__field--right
        = f.number_field :dietary_fiber, step: "0.1", class: 'food_dietary_fiber food-form__input', placeholder: "  食物繊維  (半角数字) を入力してください", min: "0", max: "1000"
      .food-form__field.clearfix
        .food-form__field--left
        .food-form__field--right
          = f.submit '更新', class: 'btn'
          = link_to '戻る', root_path, class: 'btn'
        

app/views/foods/index.html.haml
.wrapper
  = render "header"
  .contents-wrapper
    = render "side_bar"
    = render "main_contents"

app/views/foods/show.html.haml
.contents
  %h2= "〜" + @food.name + "〜"
  .food-show
    .food-data
      %table{border: "1", width: "100%", style: "border-collapse: collapse"}
        %tbody
          %tr
            %th カロリー
            %td= @food.calorie.to_s + ' (kcal)'
          %tr
            %th 糖質
            %td= @food.carbohydrate.to_s + ' (g)'
          %tr
            %th タンパク質
            %td= @food.protein.to_s + ' (g)'
          %tr
            %th 脂質
            %td= @food.fat.to_s + ' (g)'
          %tr
            %th 食塩相当量
            %td= @food.salt_equivalent.to_s + ' (g)'
          %tr
            %th 食物繊維
            %td= @food.dietary_fiber.to_s + ' (g)'
    %ul.more_list
      %li
        = link_to '編集', edit_food_path(@food.id), class: "btn"
      %li
        = link_to '削除', "/foods/#{@food.id}", method: :delete, class: "btn"
      %li
        = link_to '戻る', root_path, class: "btn"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DietaryManagement
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/managements/_form.html.haml
.form-wrapper
  = form_for @management do |f|
    - if @management.errors.any?
      #error_explanation
        %h2= "#{pluralize(@management.errors.count, "error")} prohibited this management from being saved:"
        %ul
          - @management.errors.full_messages.each do |message|
            %li= message
    .form
      = f.label :title, "表題", class: "form__label"
      = f.text_field :title, class: "form__input"
    .form
      = f.label :day, "日付", class: "form__label"
      = f.date_field :day, class: "form__input"
    .form
      %label.form__label{for: "食べ物を検索"} 食べ物を検索
      %input#food-search-field.form__input{placeholder: "食べ物の検索", type: "text"}/

    .form-food__field
      %label.form__label{for: "検索結果"} 検索結果（追加ボタンを押してください）
      #foods.js-add-food
        .form-food.js-choice-food
          %input{name: "management[food_ids][]", type: "hidden"}
          #food-search-result
    %br
    .actions
      = f.submit '登録', class: 'btn'
    = link_to '戻る', managements_path, class: 'btn'

app/views/managements/_header.html.haml
.header.clearfix
  %h2.header__title
    = "食事管理アプリ"
    %h3.header__name
      = current_user.name
      .bmi
        = "BMI " + (current_user.weight.to_f  / current_user.height.to_f / current_user.height.to_f * 10000).round(1).to_s
    %ul.header__lists
      %li.list
        = link_to "食べ物追加", new_food_path, class: 'btn'
      %li.list
        = link_to "トップに戻る", root_path, class: 'btn'
      %li.list
        = link_to "アカウント編集", edit_user_path(current_user), class: 'btn'

app/views/managements/_main_contents.html.haml
.main_contents
  .management__main-contents
    .management__main-contents__tops
      .management__main-contents__tops__left
        .management__main-contents__top
          .management__main-contents__top-title
            %h1 一日の目安 エネルギー量
            =icon("fas", "fire")
          .management__main-contents__top-data
            - if current_user.activity == 1 && current_user.gender == 1
              - target_calorie = (14.1 * current_user.weight + 620 * 1.5)
            - elsif current_user.activity == 1 && current_user.gender == 2
              - target_calorie = (10.8 * current_user.weight + 620 * 1.5)
            - elsif current_user.activity == 2 && current_user.gender == 1
              - target_calorie = (14.1 * current_user.weight + 620 * 1.75)
            - elsif current_user.activity == 2 && current_user.gender == 2
              - target_calorie = (10.8 * current_user.weight + 620 * 1.75)
            - elsif current_user.activity == 3 && current_user.gender == 1
              - target_calorie = (14.1 * current_user.weight + 620 * 2.0)
            - elsif current_user.activity == 3 && current_user.gender == 2
              - target_calorie = (10.8 * current_user.weight + 620 * 2.0)
            - else
              計算できません
            = target_calorie.round.to_s + " kcal"
        .management__main-contents__top
          .management__main-contents__top-title
            %h1 一日の目安 糖質
            =icon("fas", "bread-slice")
          .management__main-contents__top-data
            - if current_user.activity == 1 && current_user.gender == 1
              - lower_target_carbohydrate = ((14.1 * current_user.weight + 620 * 1.5) / 4 * 0.5)
              - upper_target_carbohydrate = ((14.1 * current_user.weight + 620 * 1.5) / 4 * 0.65)
            - elsif current_user.activity == 1 && current_user.gender == 2
              - lower_target_carbohydrate = ((10.8 * current_user.weight + 620 * 1.5) / 4 * 0.5)
              - upper_target_carbohydrate = ((10.8 * current_user.weight + 620 * 1.5) / 4 * 0.65)
            - elsif current_user.activity == 2 && current_user.gender == 1
              - lower_target_carbohydrate = ((14.1 * current_user.weight + 620 * 1.75) / 4 * 0.5) 
              - upper_target_carbohydrate = ((14.1 * current_user.weight + 620 * 1.75) / 4 * 0.65)
            - elsif current_user.activity == 2 && current_user.gender == 2
              - lower_target_carbohydrate = ((10.8 * current_user.weight + 620 * 1.75) / 4 * 0.5)
              - upper_target_carbohydrate = ((10.8 * current_user.weight + 620 * 1.75) / 4 * 0.65)
            - elsif current_user.activity == 3 && current_user.gender == 1
              - lower_target_carbohydrate = ((14.1 * current_user.weight + 620 * 2.0) / 4 * 0.5)
              - upper_target_carbohydrate = ((14.1 * current_user.weight + 620 * 2.0) / 4 * 0.65)
            - elsif current_user.activity == 3 && current_user.gender == 2
              - lower_target_carbohydrate = ((10.8 * current_user.weight + 620 * 2.0) / 4 * 0.5)
              - upper_target_carbohydrate = ((10.8 * current_user.weight + 620 * 2.0) / 4 * 0.65)
            - else
              - lower_target_carbohydrate = 計算できません
            = lower_target_carbohydrate.round.to_s  + " g" + " 〜 " + upper_target_carbohydrate.round.to_s  + " g"
        .management__main-contents__top
          .management__main-contents__top-title
            %h1 一日の目安 タンパク質
            =icon("fas", "fish")
          .management__main-contents__top-data
            - if current_user.activity == 1 && current_user.gender == 1
              - lower_target_protein = ((14.1 * current_user.weight + 620 * 1.5) / 4 * 0.13)
              - upper_target_protein = ((14.1 * current_user.weight + 620 * 1.5) / 4 * 0.2)
            - elsif current_user.activity == 1 && current_user.gender == 2
              - lower_target_protein = ((10.8 * current_user.weight + 620 * 1.5) / 4 * 0.13)
              - upper_target_protein = ((10.8 * current_user.weight + 620 * 1.5) / 4 * 0.2)
            - elsif current_user.activity == 2 && current_user.gender == 1
              - lower_target_protein = ((14.1 * current_user.weight + 620 * 1.75) / 4 * 0.13)
              - upper_target_protein = ((14.1 * current_user.weight + 620 * 1.75) / 4 * 0.2)
            - elsif current_user.activity == 2 && current_user.gender == 2
              - lower_target_protein = ((10.8 * current_user.weight + 620 * 1.75) / 4 * 0.13)
              - upper_target_protein = ((10.8 * current_user.weight + 620 * 1.75) / 4 * 0.2)
            - elsif current_user.activity == 3 && current_user.gender == 1
              - lower_target_protein = ((14.1 * current_user.weight + 620 * 2.0) / 4 * 0.13)
              - upper_target_protein = ((14.1 * current_user.weight + 620 * 2.0) / 4 * 0.2)
            - elsif current_user.activity == 3 && current_user.gender == 2
              - lower_target_protein = ((10.8 * current_user.weight + 620 * 2.0) / 4 * 0.13)
              - upper_target_protein = ((10.8 * current_user.weight + 620 * 2.0) / 4 * 0.2)
            - else
              計算できません
            = lower_target_protein.round.to_s  + " g" + " 〜 " + upper_target_protein.round.to_s  + " g"
        .management__main-contents__top
          .management__main-contents__top-title
            %h1 一日の目安 脂質
            =icon("fas", "bacon")
          .management__main-contents__top-data
            - if current_user.activity == 1 && current_user.gender == 1
              - lower_target_fat = ((14.1 * current_user.weight + 620 * 1.5) / 9 * 0.2)
              - upper_target_fat = ((14.1 * current_user.weight + 620 * 1.5) / 9 * 0.3)
            - elsif current_user.activity == 1 && current_user.gender == 2
              - lower_target_fat = ((10.8 * current_user.weight + 620 * 1.5) / 9 * 0.2)
              - upper_target_fat = ((10.8 * current_user.weight + 620 * 1.5) / 9 * 0.3)
            - elsif current_user.activity == 2 && current_user.gender == 1
              - lower_target_fat = ((14.1 * current_user.weight + 620 * 1.75) / 9 * 0.2)
              - upper_target_fat = ((14.1 * current_user.weight + 620 * 1.75) / 9 * 0.3)
            - elsif current_user.activity == 2 && current_user.gender == 2
              - lower_target_fat = ((10.8 * current_user.weight + 620 * 1.75) / 9 * 0.2)
              - upper_target_fat = ((10.8 * current_user.weight + 620 * 1.75) / 9 * 0.3)
            - elsif current_user.activity == 3 && current_user.gender == 1
              - lower_target_fat = ((14.1 * current_user.weight + 620 * 2.0) / 9 * 0.2)
              - upper_target_fat = ((14.1 * current_user.weight + 620 * 2.0) / 9 * 0.3)
            - elsif current_user.activity == 3 && current_user.gender == 2
              - lower_target_fat = ((10.8 * current_user.weight + 620 * 2.0) / 9 * 0.2)
              - upper_target_fat = ((10.8 * current_user.weight + 620 * 2.0) / 9 * 0.3)
            - else
              - lower_target_fat = 計算できません
            = lower_target_fat.round.to_s  + " g" + " 〜 " + upper_target_fat.round.to_s  + " g"
        .management__main-contents__top
          .management__main-contents__top-title
            %h1 一日の目安 食物繊維
            =icon("fas", "seedling")
          .management__main-contents__top-data
            %h1 20 g 以上
        .management__main-contents__top
          .management__main-contents__top-title
            %h1 一日の目安 食塩相当量
            =icon("fas", "glass-whiskey")
          .management__main-contents__top-data
            %h1 8 g 未満
        .management__main-contents__top
          .management__main-contents__top-title
            %h1 適正体重
            =icon("fas", "weight")
          .management__main-contents__top-data
            = (current_user.height.to_f * current_user.height.to_f / 10000 *22).round(1).to_s + " kg"

      -# .management__main-contents__tops__right
      -#   .management__main-contents__top
      -#     .management__main-contents__top-title
      -#       %h1 今日の摂取 エネルギー量
      -#       =icon("fas", "fire")
      -#     -if @total_calorie.present?
      -#       .management__main-contents__top-judge
      -#         - if @total_calorie < target_calorie.round
      -#           .low 不足
      -#         - elsif @total_calorie == target_calorie.round
      -#           .proper 適度
      -#         -else @total_calorie > target_calorie.round
      -#           .over 過剰
      -#       .management__main-contents__top-data
      -#         = @total_calorie.round.to_s + ' kcal'
      -#   .management__main-contents__top
      -#     .management__main-contents__top-title
      -#       %h1 今日の摂取 糖質
      -#       =icon("fas", "bread-slice")
      -#     -if @total_carbohydrate.present?
      -#       .management__main-contents__top-judge
      -#         - if @total_carbohydrate < lower_target_carbohydrate.round
      -#           .low 不足
      -#         - elsif @total_carbohydrate > lower_target_carbohydrate.round && @total_carbohydrate < upper_target_carbohydrate.round
      -#           .proper 適度
      -#         -else @total_carbohydrate > upper_target_carbohydrate.round
      -#           .over 過剰
      -#       .management__main-contents__top-data
      -#         = @total_carbohydrate.round(1).to_s + ' g'
      -#   .management__main-contents__top
      -#     .management__main-contents__top-title
      -#       %h1 今日の摂取 タンパク質
      -#       =icon("fas", "fish")
      -#     - if @total_protein.present?
      -#       .management__main-contents__top-judge
      -#         - if @total_protein < lower_target_protein.round
      -#           .low 不足
      -#         - elsif @total_protein > lower_target_protein.round && @total_protein < upper_target_protein.round
      -#           .proper 適度
      -#         -else @total_protein > upper_target_protein.round
      -#           .over 過剰
      -#       .management__main-contents__top-data
      -#         = @total_protein.round(1).to_s + ' g'
      -#   .management__main-contents__top
      -#     .management__main-contents__top-title
      -#       %h1 今日の摂取 脂質
      -#       =icon("fas", "bacon")
      -#     - if @total_fat.present?
      -#       .management__main-contents__top-judge
      -#         - if @total_fat < lower_target_fat.round
      -#           .low 不足
      -#         - elsif @total_fat > lower_target_fat.round && @total_fat < upper_target_fat.round
      -#           .proper 適度
      -#         -else @total_fat > upper_target_fat.round
      -#           .over 過剰
      -#       .management__main-contents__top-data
      -#         = @total_fat.round(1).to_s + ' g'
      -#   .management__main-contents__top
      -#     .management__main-contents__top-title
      -#       %h1 今日の摂取 食物繊維
      -#       =icon("fas", "seedling")
      -#     - if @total_dietary_fiber.present?
      -#       .management__main-contents__top-judge
      -#         - if @total_dietary_fiber < 20
      -#           .low 不足
      -#         - elsif @total_dietary_fiber == 20
      -#           .proper 適度
      -#         -else @total_dietary_fiber > 20
      -#           .over 過剰
      -#       .management__main-contents__top-data
      -#         = @total_dietary_fiber.round(1).to_s + ' g'
      -#   .management__main-contents__top
      -#     .management__main-contents__top-title
      -#       %h1 今日の摂取 食塩相当量
      -#       =icon("fas", "glass-whiskey")
      -#     - if @total_salt_equivalent.present?
      -#       .management__main-contents__top-judge
      -#         - if @total_salt_equivalent < 8
      -#           .low 不足
      -#         - elsif @total_salt_equivalent == 8
      -#           .proper 適度
      -#         -else @total_salt_equivalent > 8
      -#           .over 過剰
      -#       .management__main-contents__top-data
      -#         = @total_salt_equivalent.round(1).to_s + ' g'
      -#   .management__main-contents__top
      -#     .management__main-contents__top-title
      -#       %h1 現体重
      -#       =icon("fas", "weight")
      -#     .management__main-contents__top-judge
      -#     .management__main-contents__top-data
      -#       = current_user.weight.to_s + " kg"

    .management__main-contents__list
      %h1 記録表
      = link_to '新規登録', new_management_path, class: "btn"
      %br
      %table{ border: "1"}
        %thead
          %tr
            %th 表題
            %th 日付
            %th 食べた物
            %th カロリー
            %th 糖質
            %th タンパク質
            %th 脂質
            %th 食塩相当量
            %th 食物繊維
            %th{colspan: "2"}

        %tbody
          - @managements.each do |management|
            %tr
              %td= management.title
              %td= management.day
              - management.foods.each do |food|
                %td= food.name
                %td= food.calorie.to_s + ' (kcal)'
                %td= food.carbohydrate.to_s + ' (g)'
                %td= food.protein.to_s + ' (g)'
                %td= food.fat.to_s + ' (g)'
                %td= food.salt_equivalent.to_s + ' (g)'
                %td= food.dietary_fiber.to_s + ' (g)'
              %td
                = link_to '編集', edit_management_path(management), class: 't-btn'
                = link_to '削除', management, method: :delete, data: { confirm: '削除しますか?' }, class: 't-btn'
 

app/views/managements/edit.html.haml
.wrapper
  .contents
    %h1 編集
    = render 'form'

app/views/managements/index.html.haml
.wrapper
  = render "header"
  .contents-wrapper
    = render "main_contents"

app/views/managements/new.html.haml
.wrapper
  .contents
    %h1 新規登録
    = render 'form'